env:
  global:
    - secure: JnADJkNc3xePiRyNYz2n84Osf/ThWvOILOap2sgtC+387iTSQKXgobkpEYSK9YQqLRxmRN2fkZQ3JA4d/k3z7p6WqHPGZTcBnPdIPLvr6L3IMS7W4+FRzD3bT/zNIcyQ371H3Chtd26QCqIrDsVdfSGdqV5G1Y/Vv0MJd2kNF1EFqmwjEJWs/6q96lwvMuiPFBdoqt4yZf1tb5zEm+9zVCpXc2J41+CYLr2UpXz+3zjLOuhUaZjcKfe4t/poDwaqm6w1PwvYp9jSG84VY48zJZLR1AwgZLuNT43t3FlJKnnsqijJpg7nsxsoGVDq9OrODSkCLuVNY984aiEYnb/Q8Pi6RHeFpQaWdnO+OZz9vLfda/Wj1/+rPV2DLrOStCn7+9Lmjczs5kKR4vn70xTi81e1MaXQ7mprqwigjt5Ns9eAgwiuCnCf/KuieEa7U55k0GXr9Uzr+C0e0rlvHGi+Km+Y4CJ2LN/mGEa2hoWUwzmVFPNHDtrof/a0KqgcP3dwHG/bLc3mmgKjaqfQQgQs1JFktg4+InGIFmk8EyC9KC2bNLJSgdEvKYP9pOfjWAw8qqNtgFL81bQ1s2REsuWJuDZKNRLx3KrJlecrVxf5Fh54R9SDp39AcfWtjpdMfwz7V5uTqcUzBU+oOwOYW76je20H26C3OCcnsRugWoQgGJc=
matrix:
  include:
    - os: linux
      language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - gcc-multilib
            - g++-multilib
            - clang
            - gdb
      script:
        - mkdir Source/NativeDumpTest/bin
        - g++ Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc -std=c++11 -g
        - g++ -m32 Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc -std=c++11 -g
        - clang++ Source/NativeDumpTest/NativeDumpTest.cpp -o Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang -std=c++11 -g -D_GLIBCXX_DEBUG
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x86.gcc.coredump' -ex 'quit'
        - gdb --batch Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang -ex 'r' -ex 'generate-core-file Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.clang.coredump' -ex 'quit'
        - echo $MY_TEST
        - echo $MY_TEST2
        - echo $TRAVIS_BUILD_NUMBER
        - curl -T Source/NativeDumpTest/bin/NativeDumpTest.linux.x64.gcc.coredump -usouthpolenator:$BINTRAY_API_KEY https://api.bintray.com/content/southpolenator/WinDbgCs_dumps/NativeDumpTest/2.0/NativeDumpTest.linux.x64.gcc.coredump
        - for file in Source/NativeDumpTest/bin/*; do echo $file; done
