version: 1.0.{build}
skip_commits:
  message: /.*dumps.*/

image:
  - Visual Studio 2013
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( cd Source\ExceptionDumper32 )
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( dotnet restore )
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( dotnet msbuild )
  - IF NOT "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( cd ..\..\ )
  - SET project_root=C:\projects\windbgcs-dumps
  - SET DUMPER=%project_root%\Source\ExceptionDumper\bin\Debug\net461\ExceptionDumper.exe
  - IF NOT EXIST %DUMPER% ( SET DUMPER=%project_root%\bin\ExceptionDumper.exe )
  - ECHO %DUMPER%
  - SET DUMPER32=%project_root%\Source\ExceptionDumper32\bin\Debug\net461\ExceptionDumper32.exe
  - IF NOT EXIST %DUMPER32% ( SET DUMPER32=%project_root%\bin\ExceptionDumper32.exe )
  - ECHO %DUMPER32%
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x64.Release.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x86.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( msbuild Source\NativeDumpTest\NativeDumpTest.x86.Release.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo )
  - SET gccpath=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
  - SET ORIGINAL_PATH=%PATH%
  - SET PATH=%gccpath%;%ORIGINAL_PATH%
  - IF EXIST %gccpath% ( %gccpath%\g++ %project_root%\Source\NativeDumpTest\NativeDumpTest.cpp -o %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -std=c++11 -g )
  - IF EXIST %gccpath% ( %DUMPER% -a %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -d %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.mdmp )
  - SET gccpath=C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
  - SET PATH=%gccpath%;%ORIGINAL_PATH%
  - IF EXIST %gccpath% ( %gccpath%\g++ %project_root%\Source\NativeDumpTest\NativeDumpTest.cpp -o %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -std=c++11 -g )
  - IF EXIST %gccpath% ( %DUMPER32% -a %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -d %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.mdmp )
  - SET BRANCH=Appeyor/%APPVEYOR_BUILD_ID%
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2013" ( SET BRANCH=VS2013.%BRANCH% )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET BRANCH=VS2015.%BRANCH% )
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" ( SET BRANCH=VS2017.%BRANCH% )
  - git config --global user.email "autopr@github.com"
  - git config --global user.name "autopr"
  - git checkout -b %BRANCH%
  - xcopy /Y Source\NativeDumpTest\bin\*.exe .\
  - xcopy /Y Source\NativeDumpTest\bin\*.pdb .\
  - xcopy /Y Source\NativeDumpTest\bin\*.*dmp .\
  - git add .
  - git commit -m "Updating dumps"
  - git remote add origin-autopr https://${9c9bd7ac46f0c96c4d7651a7765c173736a2f1d0}@github.com/southpolenator/WinDbgCs_dumps.git
  - git push --quiet --set-upstream origin-autopr %BRANCH%
  - git pull-request

artifacts:
  - path: '**\bin\*.exe'
  - path: '**\bin\*.pdb'
  - path: '**\bin\*.*dmp'
