version: 1.0.{build}
skip_commits:
  message: /.*dumps.*/

image:
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
  - cd Source\ExceptionDumper32
  - dotnet restore
  - dotnet msbuild
  - cd ..\..\
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.Release.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x86.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x86.Release.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo
  - SET gccpath=C:\MinGW\bin
  - IF EXIST %gccpath% (
      %gccpath%\g++ Source\NativeDumpTest\NativeDumpTest.cpp -o Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -std=c++11 -g
      xcopy /D /Y %gccpath%\libgcc_s_dw2-1.dll Source\NativeDumpTest\bin\
      xcopy /D /Y %gccpath%\libstdc++-6.dll Source\NativeDumpTest\bin\
      Source\ExceptionDumper32\bin\Debug\net461\ExceptionDumper32.exe -a Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -d Source\NativeDumpTest\bin\NativeDumpTest.gcc.mdmp
      del Source\NativeDumpTest\bin\libgcc_s_dw2-1.dll"
      del Source\NativeDumpTest\bin\libstdc++-6.dll"
    )

artifacts:
  - path: '**\*.*dmp'
