version: 1.0.{build}
skip_commits:
  message: /.*dumps.*/

image:
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
  - cd Source\ExceptionDumper32
  - dotnet restore
  - dotnet msbuild
  - cd ..\..\
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.vcxproj /p:Configuration=Debug;Platform=x64 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x64.Release.vcxproj /p:Configuration=Release;Platform=x64 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x86.vcxproj /p:Configuration=Debug;Platform=Win32 /verbosity:minimal /nologo
  - msbuild Source\NativeDumpTest\NativeDumpTest.x86.Release.vcxproj /p:Configuration=Release;Platform=Win32 /verbosity:minimal /nologo
  - SET gccpath=C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\bin
  - SET project_root=C:\projects\windbgcs-dumps
  - IF EXIST %gccpath% ( SET PATH=%gccpath%;%PATH% )
  - IF EXIST %gccpath% ( %gccpath%\g++ %project_root%\Source\NativeDumpTest\NativeDumpTest.cpp -o %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -std=c++11 -g )
  - IF EXIST %gccpath% ( copy %gccpath%\libgcc_s_seh-1.dll %project_root%\Source\NativeDumpTest\bin\ )
  - IF EXIST %gccpath% ( copy %gccpath%\libstdc++-6.dll %project_root%\Source\NativeDumpTest\bin\ )
  - IF EXIST %gccpath% ( %project_root%\Source\ExceptionDumper\bin\Debug\net461\ExceptionDumper.exe -a %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.exe -d %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.x64.gcc.mdmp )
  - IF EXIST %gccpath% ( del %project_root%\Source\NativeDumpTest\bin\libgcc_s_seh-1.dll" )
  - IF EXIST %gccpath% ( del %project_root%\Source\NativeDumpTest\bin\libstdc++-6.dll" )
  - IF EXIST %gccpath% ( %gccpath%\g++ -m32 %project_root%\Source\NativeDumpTest\NativeDumpTest.cpp -o %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -std=c++11 -g )
  - IF EXIST %gccpath% ( copy %gccpath%\libgcc_s_seh-1.dll %project_root%\Source\NativeDumpTest\bin\ )
  - IF EXIST %gccpath% ( copy %gccpath%\libstdc++-6.dll %project_root%\Source\NativeDumpTest\bin\ )
  - IF EXIST %gccpath% ( %project_root%\Source\ExceptionDumper32\bin\Debug\net461\ExceptionDumper32.exe -a %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.exe -d %project_root%\Source\NativeDumpTest\bin\NativeDumpTest.gcc.mdmp )
  - IF EXIST %gccpath% ( del %project_root%\Source\NativeDumpTest\bin\libgcc_s_seh-1.dll" )
  - IF EXIST %gccpath% ( del %project_root%\Source\NativeDumpTest\bin\libstdc++-6.dll" )

artifacts:
  - path: '**\*.*dmp'
